name: Build HM app 
on: push
  
jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.13.9'
          
      - name: Clone project
        run: git clone https://github.com/anandnet/Harmony-Music.git

      - name: Flutter doctor
        run: flutter doctor
        
      - name: Install project dependencies
        working-directory: ./Harmony-Music
        run: flutter pub get
        
      - name: Build android apk
        working-directory: ./Harmony-Music
        run: flutter build apk --split-per-abi --release

      - name: Upload apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./Harmony-Music/build/app/outputs/flutter-apk/*apk

