name: Build HM app 
on: push
  
jobs:
  build-android-apk-and-linux-deb:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.13.9'
          
      - name: Clone project
        run: git clone https://github.com/anandnet/Harmony-Music.git

      - name: Flutter doctor
        run: flutter doctor
        
      - name: Install project dependencies
        working-directory: ./Harmony-Music
        run: flutter pub get
        
      - name: Build android apk
        working-directory: ./Harmony-Music
        run: |
          flutter build apk --split-per-abi --release
          flutter build apk

      - name: Upload apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: Harmony music apk
          path: ./Harmony-Music/build/app/outputs/flutter-apk/*apk
          
      - name: install required deps for linux package
        run: |
          sudo apt-get install libmpv-dev mpv libayatana-appindicator3-dev ninja-build libgtk-3-dev
          
      - name: Flutter doctor
        run: flutter doctor

      - name: Build linux deb package
        working-directory: ./Harmony-Music
        run: |
          dart pub global activate flutter_distributor
          flutter_distributor package --platform linux --targets deb
          
      - name: Upload linux deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: Harmony music linux deb file
          path: ./Harmony-Music/build/dist/*
          

