
name: get ios file

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ios-file:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.13.9'

      - name: Clone project
        run: git clone https://github.com/anandnet/Harmony-Music.git

      - name: Flutter doctor
        run: flutter doctor
        
      - name: Install project dependencies
        working-directory: ./Harmony-Music
        run: flutter pub get

      - name: Update lang data
        working-directory: ./Harmony-Music
        run: dart localization/generator.dart

      - name: Set update check flag to true
        working-directory: ./Harmony-Music/lib/utils
        run: echo "const updateCheckFlag = true;" > update_check_flag_file.dart

      - name: release ios package
        working-directory: ./Harmony-Music
        run: flutter build ios --release --no-codesign

      - name: Upload ios file artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios file
          path: ./Harmony-Music/ios/*