name: Flutter Build for Windows

on:
  push:
    branches:
      - main  # Cambia "main" si tu rama principal tiene otro nombre.
  pull_request:
    branches:
      - main  # Cambia "main" si tu rama principal tiene otro nombre.

jobs:
  build:
    runs-on: windows-latest  # Ejecuta en una máquina virtual con Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Obtiene tu código desde el repositorio

    - name: Set up Flutter
      uses: subosito/flutter-action@v2  # Configura Flutter
      with:
        flutter-version: 'stable'  # Usa la versión estable de Flutter

    - name: Install dependencies
      run: flutter pub get  # Instala las dependencias de Flutter

    - name: Build Windows
      run: flutter build windows --release  # Compila el proyecto para Windows en modo release

    - name: Upload artifact
      uses: actions/upload-artifact@v2  # Sube el archivo .exe generado como artefacto
      with:
        name: flutter-windows-exe  # Nombre del artefacto
        path: build/windows/runner/Release/*.exe  # Ruta al archivo .exe generado
